# Generated by Django 3.1.1 on 2020-10-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forex_blog', '0003_auto_20201007_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Forex_blog.post'),
        ),
    ]
